name: Generate Pacman Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"   # รันทุกวัน
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate pacman graph
        uses: Platane/pacman-contribution-graph@main
        with:
          github_user_name: Pond32145

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Generate pacman contribution graph" || exit 0
          git push
